package restController;


/**
 * @author Lang
 * 
 *	@RestController is a combination of @Controller and @RespondBody
 *	The object type response generated by @RestController will be JSON by default (and getter of the Class must be defined)
 */
public class Info {

}
